RusimbiP/Teamwork

- UI/css/nav.css
Have a responsive navigation bar
Have a responsive navigation bar working on all devices
By navigating [Teamwork](https://rusimbipatrick.github.io/Teamwork/)
- Check if the task mentioned above was completed.
N/A
#168821534
> #168821534 Make navigation bar responsive

- UI/css/nav.css
> Merge into gh-pages

- UI/css/nav.css
> Revert "Merge into gh-pages"

- .codeclimate.yml
- server/controllers/user.js
- server/helpers/helper.js
- server/models/user.js
- server/routes/user.js
- server/services/user.js
- server/tests/user.test.js
Have signup endpoint working
`POST api/v1/auth/signin`
After cloning this repo, cd into it and RUN **npm start** or npm run dev(to run in deveeloper mode)
- Using Postman test the endpoint above
N/A
#168497663
N/A
N/A
> #168497663 Build sign in Endpoint

- UI/css/dashboard.css
- UI/js/model.js
- UI/pages/dashboard.html
Have the dashboard restyled
- A picture of the article, 
- A small snippet/preview of the article,
- Edit button
- Delete button
-  When the user clicks on the delete button, It should display a modal just to confirm the action
By visiting the [dashboard](https://rusimbip.github.io/Teamwork/UI/pages/dashboard.html) check if all tasks have been completed
N/A
#168862377
N/A
> #168862377 Restyle Dashboard

- UI/css/comment.css
- UI/pages/article.html
Have a dummy comment build
- A picture of the comment author
- A timestamp
- A comment
By visiting the [Read more](https://rusimbip.github.io/Teamwork/UI/pages/article.html?) check if all tasks have been completed
N/A
#168866115 
N/A
> #168866115 Build UI for a dummy comment

- UI/css/create.css
Have a margin added on the text editor
- A margin added on the **left-side** of text editor
By visiting the [Create article page](https://rusimbip.github.io/Teamwork/UI/pages/create.html) Use a mobile phone view to check if all the task above has been completed
N/A
#168868764
N/A
> #168868764 Add margin on text editor

- UI/css/dashboard.css
- UI/css/editprofile.css
- UI/css/nav.css
- UI/pages/article.html
- UI/pages/create.html
- UI/pages/dashboard.html
- UI/pages/feeds.html
Have a  collapsible navigation bar 
- Logo
- All navigation links
- Collapsibility
By navigating [Teamwork](https://rusimbip.github.io/Teamwork/UI/) check if all tasks above have been completed
N/A
#168870448
N/A
> #168870448 Build a collapsible navigation bar

- UI/css/editprofile.css
- UI/css/signup.css
- UI/pages/editprofile.html
Have  navigation bar on edit profile page and improved responsiveness
-Put the navigation bar on the edit profile page
- improved responsiveness
By navigating [Teamwork](https://rusimbip.github.io/Teamwork/UI/) check if all tasks above have been completed
N/A
#168870448
N/A
> #168870448 Put the navigation bar on the edit profile page and improve responsiveness 

- server/app.js
- server/controllers/comment.js
- server/helpers/validations.js
- server/middleware/verifyToken.js
- server/models/article.js
- server/models/comment.js
- server/routes/article.js
- server/routes/comment.js
- server/routes/user.js
- server/services/article.js
- server/services/comment.js
- server/tests/article.test.js
Have comment-on-article endpoint built
`POST /api/v1/articles/:articleId/comments`
- To test authentication, ad this to the header: Get token from login endpoint 
N/A
#168497666
N/A
> #168497666 Build comment-on-article endpoint 

- server/controllers/article.js
- server/models/article.js
- server/models/comment.js
- server/routes/article.js
- server/services/article.js
- server/tests/article.test.js
Have view specific article endpoint built
`GET  /api/v1/articles/:articleId`
N/A
#168497669
N/A
> #168497669 Build view specific article endpoint

- package.json
- server/helpers/helper.js
- server/helpers/validations.js
- server/middleware/errorHandler.js
- server/routes/article.js
- server/services/user.js
- server/tests/user.test.js
Have responses and validation fixed
Fix validation in the following endpoints:
`POST /api/v1/articles/`
`POST /api/v1/auth/signin`
`POST /api/v1/articles`
`POST localhost:3000/api/v1/articles/:articleId/comments`
`PATCH /api/v1/articles/:articleId`
`GET /api/v1/articles/:articleId`
- To test authentication, ad this to the header: Get token from login endpoint 
N/A
#168937381
N/A
> #168937381 Fix responses and validation

- server/controllers/article.js
- server/models/article.js
- server/routes/article.js
- server/services/article.js
Have delete article endpoint built
`DELETE  /api/v1/articles/`
N/A
#168497675
N/A
N/A
> #168497675 Build delete article Endpoint

- server/controllers/article.js
- server/models/article.js
- server/routes/article.js
- server/services/article.js
Have view feed article endpoint built
`GET  /api/v1/articles/feed`
N/A
#168827956
N/A
> #168827956 Build view feed Endpoint

- .travis.yml
- server/v2/app.js
- server/v2/controllers/article.js
- server/v2/controllers/user.js
- server/v2/db/migrations/migrateUp.js
- server/v2/db/queries.js
- server/v2/middleware/verifyToken.js
- server/v2/routes/article.js
- server/v2/routes/user.js
- server/v2/services/article.js
- server/v2/services/user.js
- server/v2/tests/user.test.js
Have signin endpoint working
`POST api/v2/auth/signin`
After cloning this repo, cd into it and RUN **npm start** or npm run dev(to run in developer mode)
- Using Postman test the endpoint above
N/A
#168977884 
N/A
> #168977884 Build sign in Endpoint using PostgreSQL

- .travis.yml
- server/v2/db/mockData.js
- server/v2/middleware/verifyToken.js
- server/v2/services/article.js
- server/v2/services/user.js
- server/v2/tests/article.test.js
- server/v2/tests/user.test.js
Have write article endpoint built
`POST /api/v2/articles`
- To test authentication, ad this to the header: Get token from login endpoint 
N/A
#168497665
N/A
> #168978258 Build write article Endpoint using PostgreSQL 

- server/v2/controllers/article.js
- server/v2/controllers/user.js
- server/v2/db/migrations/migrateUp.js
- server/v2/db/queries.js
- server/v2/helpers/validations.js
- server/v2/routes/article.js
- server/v2/routes/user.js
- server/v2/services/article.js
- server/v2/services/user.js
- server/v2/tests/article.test.js
Have edit article endpoint built
`PATCH /api/v2/articles/`
N/A
#168978363
N/A
> #168978363 Build edit article Endpoint using PostgreSQL 

- server/v2/app.js
- server/v2/controllers/article.js
- server/v2/db/queries.js
- server/v2/routes/feed.js
- server/v2/services/article.js
- server/v2/tests/article.test.js
- server/v2/tests/user.test.js
Have view feed article endpoint built
`GET  /api/v2/articles/feed`
N/A
#168978338
N/A
> #168978338 Build view feed Endpoint using PostgreSQL

- server/v2/controllers/article.js
- server/v2/db/dummyData.js
- server/v2/db/migrations/migrateUp.js
- server/v2/db/queries.js
- server/v2/routes/article.js
- server/v2/services/article.js
- server/v2/tests/article.test.js
Have delete article endpoint built
`DELETE  /api/v2/articles/`
N/A
#168978369 
N/A
> #168978369 Build delete article Endpoint using PostgreSQL 

- server/v2/db/mockData.js
- server/v2/helpers/validations.js
- server/v2/routes/article.js
- server/v2/services/article.js
- server/v2/tests/article.test.js
Have validations for edit article endpoint
Have the validations for the following:
- tittle, subtitle, article
- req.body
N/A
#169074542
N/A
N/A
> #169074542 validate input before editing an article

- server/v2/db/queries.js
Have view feed endpoint fixed
`GET  /api/v2/feed`
Have the articles returned by LIFO
N/A
#169076757 
N/A
N/A
> #169076757 Fix view feed Endpoint to return articles by LIFO

- server/v2/db/queries.js
- server/v2/middleware/verifyToken.js
- server/v2/services/article.js
- server/v2/services/user.js
- server/v2/tests/article.test.js
- server/v2/tests/user.test.js
Have edit article endpoint fixed and login endpoint fixed
Have 401 status code on the login failure
Have authoer object returned after editing an article
Have the articles returned by LIFO
N/A
#169076757 
N/A
N/A
> #169077123 Fix status codes and response Objects

- server/v2/db/migrations/migrateUp.js
- server/v2/db/queries.js
- server/v2/services/article.js
Have comment-on-article endpoint built
`POST /api/v2/articles/:articleId/comments`
`GET /api/v2/articles/:articleId`
N/A
#168978274
N/A
> #168978274 Build comment on article feature using PostgreSQL 
